%Matpower call
addpath( ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\lib', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\lib\t', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\data', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\mips\lib', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\mips\lib\t', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\most\lib', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\most\lib\t', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\mptest\lib', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\mptest\lib\t', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\maxloadlim', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\maxloadlim\tests', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\maxloadlim\examples', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\misc', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\reduction', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\sdp_pf', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\se', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\smartmarket', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\state_estimator', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\syngrid\lib', ...
    'C:\Users\mferr\OneDrive\Documents\Master\TFM\matpower7.0\extras\syngrid\lib\t', ...
    '-end' );


runpf ('case4gs')